version: "3.9"

services:
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      auth.env

  mariadb:
    image: lscr.io/linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${ROOT_ACCESS_PASSWORD}
      - TZ=${TIME_ZONE}
      - MYSQL_DATABASE=${DB_NAME} #optional
      - MYSQL_USER=${DB_USER} #optional
      - MYSQL_PASSWORD=${DB_PASSWORD} #optional
      #- REMOTE_SQL=http://URL1/your.sql,https://URL2/your.sql #optional
    volumes:
      - ./.sql:/config
    ports:
      - 3306:3306
    restart: unless-stopped

