version: "3.9"

networks:
  newNet:
    driver: bridge

services:

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      auth/.env
    networks:
      - newNet

  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file:
      api/.env
    networks:
      - newNet

  monitor:
    build:
      context: ./monitor
      dockerfile: Dockerfile
    env_file:
      monitor/.env
    networks:
      - newNet

  mariadb:
    image: lscr.io/linuxserver/mariadb
    container_name: mariadb
    networks:
      - newNet
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${ROOT_ACCESS_PASSWORD}
      - TZ=${TIME_ZONE}
      - MYSQL_DATABASE=${DB_NAME} #optional
      - MYSQL_USER=${DB_USER} #optional
      - MYSQL_PASSWORD=${DB_PASSWORD} #optional
      #- REMOTE_SQL=http://URL1/your.sql,https://URL2/your.sql #optional
    volumes:
      - ./.sql:/config
    ports:
      - 3306:3306
    restart: unless-stopped

  rtmp:
    image: alqutami/rtmp-hls
    container_name: rtmp-server
    networks:
      - newNet
    ports:
      - 8080:8080
      - 1935:1935
    volumes:
      - ./webui/admin/:/usr/local/nginx/html/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
